apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 15
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      imagePullSecrets:
        - name: teamregistry
      containers:
      - name: gamebot
        image: ghcr.io/azure-adventure-day/azure-adventure-day-coach/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "be292741-80eb-4e8e-b5c1-9476756053f7"
          - name: "FF_BETS"
            value: "true"              
